services:
  # FAST-API
  srv-api-fast:
    container_name: srv-api-fast
    build:
      context: ./api-fast
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://root:admin@44.203.113.190:27017
    networks:
      - back-tier

  # WORKER
  worker-load:
    container_name: srv-worker
    build:
      context: ./worker
    networks:
      - back-tier
    environment:
      - REDIS_HOST=44.203.113.190
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://root:admin@44.203.113.190/tecsup?authSource=admin
      - API_ENDPOINT=http://srv-api-fast:5000/api/recommendations/from-url
      - DIRECCION=http://34.227.7.159:4000
    # ports:
    #   - "8081:80"

networks:
  back-tier:

volumes:
  mongo-data:
  redis-data: