services:
  # FAST-API
  python-app:
    container_name: srv-api-fast
    build:
      context: ./api-fast
    ports:
      - "5000:5000"
    depends_on:
      - db-mongo
    environment:
      - MONGO_URI=mongodb://root:admin@34.227.7.159:27017
    networks:
      - back-tier

  # WORKER
  worker-load:
    container_name: srv-worker
    build:
      context: ./worker
    networks:
      - back-tier
    # environment:
    #   - REDIS_HOST=ch-redis
    #   - REDIS_PORT=6379
    #   - MONGODB_URI=mongodb://root:admin@db-mongo:27017/test?authSource=admin
    ports:
      - "8081:80"

networks:
  back-tier:

volumes:
  mongo-data:
  redis-data: